apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-exa-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: 1=registry.sikademo.com/exa/hello-exa:master
    argocd-image-updater.argoproj.io/1.helm.image-spec: image
    argocd-image-updater.argoproj.io/1.update-strategy: digest
    argocd-image-updater.argoproj.io/1.force-update: 'true'
    argocd-image-updater.argoproj.io/1.platforms: linux/amd64
    # dev/hello-exa-dev = {{.Release.Namespace}}/{{.Release.Name}}-docker
    argocd-image-updater.argoproj.io/1.pull-secret: pullsecret:dev/hello-exa-dev-docker
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: ./charts/one-image
    helm:
      valuesObject:
        host: example-dev.k8s.sikademo.com
        image: registry.sikademo.com/exa/hello-exa:master
        containerPort: 8000
        dockerRegistry: registry.sikademo.com
        dockerRegistryAuth: b25kcmVqc2lrYTphc2RmYXNkZg==
